### ISSUE TITLE
Missing instructions regarding /etc/sysMonDash/config.xml

### ISSUE THREAD

**Issue by epleterte** [nuxsmin/sysMonDash#7]
Hey,
I see no mention of /etc/sysMonDash/config.xml - it'd be nice to add some simple instructions for this. I did something like this:

```
mkdir /etc/sysMonDash
touch /etc/sysMonDash/config.xml
chown apache:apache /etc/sysMonDash/config.xml
```

Being able to place the config somewhere else would be nice too.

**Comment by nuxsmin** [comment]
Hi @epleterte ,

there is some points at https://github.com/nuxsmin/sysMonDash/wiki that can be useful for setup SMD, but you are right, there isn't any instructions about those steps...

About config placement, it's quite difficult to change it on demand, because on first initialization it should know where to read/store the config file, and then modify the php file from where it's being called, and that is an unwanted action. Another option is to modify that php base file by hand, but it will put some extra actions to the end users, that usually wants plug&play :)

**Comment by nuxsmin** [comment]
Done
